baseURL = "http://example.org/"
languageCode = "en-us"
title = "KubeGene"
theme = "theer"


[Params]
  RSSLink = "/index.xml"
  author = "" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "What is KubeGene?"
    weight = 10
    url = "/docs/about/"
[[menu.main]]
    name = "Getting Started"
    weight = 20
    url = "/docs/started/"
[[menu.main]]
    name = "Guides"
    weight = 30
    url = "/docs/guides/"
[[menu.main]]
    name = "Design"
    weight = 30
    url = "/docs/design/"
[[menu.main]]
    name = "GitHub"
    weight = 40
    url = "https://github.com/kubegene/"

