baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kubegene"
theme = "theer"


[Params]
  RSSLink = "/index.xml"
  author = "" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "What is Kubegene?"
    weight = 10
    url = "/docs/about/"
[[menu.main]]
    name = "Getting Started"
    weight = 20
    url = "/docs/started/"
[[menu.main]]
    name = "Guides"
    weight = 30
    url = "/docs/guides/"
[[menu.main]]
    name = "GitHub"
    weight = 40
    url = "https://github.com/kubeflow/"

[[menu.docs]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/docs/about/"
[[menu.docs]]
  name = "Getting Started"
  weight = 2
  identifier = "started"
  url = "/docs/started/"
[[menu.docs]]
  name = "Guides"
  weight = 3
  identifier = "guides"
  url = "/docs/guides/"
[[menu.docs]]
  name = "Components"
  weight = 4
  parent = "guides"
  identifier = "components"
  url = "/docs/guides/components/"
[[menu.docs]]
  name = "GKE"
  weight = 5
  parent = "guides"
  identifier = "gke"
  url = "/docs/guides/gke/"
